name: yes24_crawler

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: |
          npm install
      - name: Run main.js
        run: |
          node main.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
